# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sI1K_7id9VD4J4UY1haaiTz8GbvG-ay7
"""

import requests
from bs4 import BeautifulSoup
import time
import json

HEADERS = {'User-Agent': 'Mozilla/5.0 (educational research)'}

URLS = [
    # Main pages
    "https://www.iitj.ac.in",
    "https://www.iitj.ac.in/main/en/introduction",
    "https://www.iitj.ac.in/main/en/history",
    "https://www.iitj.ac.in/main/en/institute-reports",
    "https://www.iitj.ac.in/main/en/chairman",
    "https://www.iitj.ac.in/main/en/director",
    "https://www.iitj.ac.in/main/en/deputy-director",
    "https://www.iitj.ac.in/main/en/sustainability-policy",
    "https://www.iitj.ac.in/main/en/campus-infrastructure",
    "https://www.iitj.ac.in/office-of-director/en/office-of-director",
    "https://www.iitj.ac.in/bioscience-bioengineering",
    "https://www.iitj.ac.in/bioscience-bioengineering/en/undergraduate-program",
    "https://www.iitj.ac.in/bioscience-bioengineering/en/postgraduate-program",
    "https://www.iitj.ac.in/bioscience-bioengineering/en/doctorial-program",
    "https://www.iitj.ac.in/chemistry/en/chemistry",
    "https://www.iitj.ac.in/chemistry/en/about-research",
    "https://www.iitj.ac.in/chemistry/en/ongoing-projects",
    "https://www.iitj.ac.in/chemistry/en/completed-projects",
    "https://sites.google.com/iitj.ac.in/bschemistryiitj/home",
    "https://www.iitj.ac.in/chemistry/en/post-graduate-program",

    "https://www.iitj.ac.in/chemistry/en/doctoral-program",
    "https://www.iitj.ac.in/chemistry/en/regulations",
    "https://www.iitj.ac.in/chemical-engineering/",
    "https://www.iitj.ac.in/chemical-engineering/en/ongoing-projects",
    "https://www.iitj.ac.in/chemical-engineering/en/undergraduate-program",
    "https://www.iitj.ac.in/chemical-engineering/en/postgraduate-program",
    "https://www.iitj.ac.in/chemical-engineering/en/doctoral-program",
    "https://iitj.ac.in/office-of-academics/en/academic-regulations",
    "https://www.iitj.ac.in/civil-and-infrastructure-engineering/",

    "https://www.iitj.ac.in/civil-and-infrastructure-engineering/en/btech",
    "https://www.iitj.ac.in/civil-and-infrastructure-engineering/en/mtech-in-energy-infrastructure",
    "https://www.iitj.ac.in/computer-science-engineering/",
    "https://www.iitj.ac.in/computer-science-engineering/en/undergraduate-programs",
    "https://www.iitj.ac.in/computer-science-engineering/en/postgraduate-programs",
    "https://www.iitj.ac.in/computer-science-engineering/en/programs-for-working-professionals",
    "https://www.iitj.ac.in/computer-science-engineering/en/doctoral-programs",
    "https://www.iitj.ac.in/computer-science-engineering/en/faculty-achievements"
]

def scrape_page(url):
    try:
        r = requests.get(url, headers=HEADERS, timeout=10)
        if r.status_code != 200:
            print(f"  SKIP {url} ({r.status_code})")
            return None
        soup = BeautifulSoup(r.text, 'html.parser')

        # Remove nav, footer, scripts, styles
        for tag in soup(['nav', 'footer', 'script', 'style', 'header',
                         'aside', 'noscript', 'iframe', 'form']):
            tag.decompose()

        # Get all visible text
        text = soup.get_text(separator=' ', strip=True)

        # Basic cleanup
        import re
        text = re.sub(r'\s+', ' ', text)
        text = text.strip()

        print(f"  OK  {url} ({len(text)} chars)")
        return text
    except Exception as e:
        print(f"  ERR {url}: {e}")
        return None

print("Scraping IIT Jodhpur pages...")
documents = {}
for url in URLS:
    text = scrape_page(url)
    if text and len(text) > 200:
        documents[url] = text
    time.sleep(1)  

# Save to file
with open('iitj_scraped.json', 'w', encoding='utf-8') as f:
    json.dump(documents, f, ensure_ascii=False, indent=2)

print(f"\nDone! Scraped {len(documents)} pages → saved to iitj_scraped.json")
print(f"Total characters: {sum(len(v) for v in documents.values())}")

